"""Categorized word banks for sentence generation."""

# ── nouns (singular) ─────────────────────────────────────────────────────────

NOUNS_EASY = [
    "cat", "dog", "bird", "fish", "tree", "road", "sun", "moon", "rain",
    "book", "door", "house", "wall", "room", "bed", "chair", "table", "lamp",
    "cup", "hat", "coat", "shoe", "bag", "box", "key", "bell", "boat", "car",
    "bus", "hill", "lake", "farm", "park", "shop", "town", "school",
    "path", "gate", "yard", "roof", "fire", "wind", "snow", "sky", "star",
    "rock", "leaf", "hand", "face", "eye", "song", "game", "ball", "toy",
    "boy", "girl", "man", "child", "baby", "king", "cook", "nurse", "clerk",
    "fox", "bear", "deer", "wolf", "frog", "duck", "goat", "horse", "mouse",
    "ship", "train", "plane", "bridge", "clock", "phone", "light", "flag",
    "gift", "cake", "soup", "bread", "milk", "rose", "seed", "nest", "pond",
    "coin", "rope", "drum", "ring", "map", "pen", "page", "sign", "step",
    "meal", "dream", "smile", "voice", "story", "color", "night", "river",
    "stone", "cloud", "grass", "floor", "plate", "glass", "shirt", "dress",
    "arm", "leg", "head", "neck", "foot", "bone", "hair", "tooth",
    "egg", "pie", "jam", "tea", "nut", "corn", "rice", "pear",
    "vine", "clay", "dust", "sand", "wave", "tide", "field", "stream",
    "ant", "bee", "owl", "pig", "hen", "cub", "crow", "hawk",
    "fork", "knife", "spoon", "bowl", "pot", "pan", "jar", "tray",
    "bank", "port", "cave", "shed", "bench", "fence", "lane", "trail",
    "rule", "word", "line", "mark", "note", "spot", "job", "task",
    "chain", "wheel", "hook", "nail", "shelf", "frame", "tape", "straw",
    "beach", "storm", "flame", "frost", "fog", "marsh", "branch", "trunk",
    # ── expanded ──
    "arch", "axe", "badge", "bait", "barn", "base", "bead", "beam", "belt",
    "blade", "blast", "blaze", "block", "bloom", "bolt", "bond", "booth",
    "braid", "brass", "brick", "brook", "brush", "bulb", "bump", "bunch",
    "burst", "cabin", "cage", "cane", "cape", "cart", "chalk", "chest",
    "chin", "clam", "claw", "cliff", "cloth", "colt", "comb", "cone",
    "cord", "cork", "couch", "crack", "crane", "crate", "crest", "crop",
    "crown", "crust", "curl", "dent", "ditch", "dock", "dome", "dove",
    "drain", "drift", "dusk", "elm", "fawn", "feast", "fig", "fist",
    "flock", "foam", "fold", "forge", "fort", "glen", "globe", "glove",
    "gorge", "grape", "grip", "grove", "gulf", "gust", "hare", "harp",
    "heap", "hedge", "herb", "herd", "hive", "hood", "hoop", "horn",
    "hound", "hut", "jaw", "jewel", "knot", "lace", "ledge", "lens",
    "lid", "lime", "lodge", "loft", "lump", "mane", "mask", "mast",
    "mat", "maze", "mill", "mist", "mold", "mound", "mug", "mule",
    "oar", "ore", "oven", "palm", "paste", "patch", "paw", "peak",
    "peel", "pier", "pine", "plank", "plum", "pole", "porch", "prism",
    "prize", "pulse", "quill", "raft", "ramp", "raven", "reed", "reef",
    "ridge", "rim", "roar", "robe", "rod", "root", "sack", "sage",
    "scar", "scent", "seal", "shaft", "shawl", "silk", "slab", "slate",
    "sleeve", "sling", "slope", "slot", "snail", "span", "spark", "spear",
    "spike", "spool", "spray", "stain", "stake", "stalk", "stem", "stew",
    "stitch", "stool", "strand", "strap", "stump", "thorn", "tile", "tint",
    "torch", "trap", "trench", "trim", "trout", "tusk", "twig", "vale",
    "veil", "vent", "volt", "vow", "wand", "wasp", "wax", "web", "wedge",
    "whip", "wick", "wreath", "wren", "yarn", "yoke", "broth", "cloak",
    "flint", "flask", "gown", "hatch", "loom", "moth", "notch", "plume",
    "pouch", "rift", "rust", "scalp", "scroll", "shrub", "skull", "spire",
    "sprout", "stag", "stripe", "surge", "swamp", "thud", "wreck", "crib",
    "den", "dew", "dose", "flap", "gap", "gem", "grin", "growl", "hymn",
    "itch", "kiln", "knob", "latch", "ledge", "limp", "mink", "moat",
    "nook", "oath", "ploy", "prop", "rag", "rink", "rut", "shack",
    "shard", "skit", "slab", "slum", "smog", "snag", "snare", "soot",
    "splint", "sprig", "squid", "stint", "strut", "sulk", "swirl", "tang",
    "tarp", "throb", "thud", "tract", "trawl", "trove", "tuft", "vault",
    "welt", "whirl", "wisp", "zinc",
]

NOUNS_MEDIUM = [
    "garden", "village", "harbor", "mountain", "library", "market", "temple",
    "castle", "forest", "island", "valley", "desert", "meadow", "canyon",
    "palace", "cottage", "chapel", "tavern", "museum", "prison", "tower",
    "fountain", "orchard", "vineyard", "glacier", "volcano", "plateau",
    "captain", "soldier", "merchant", "painter", "scholar", "servant",
    "stranger", "teacher", "farmer", "hunter", "sailor", "doctor",
    "traveler", "prisoner", "guardian", "builder", "driver", "author",
    "journal", "portrait", "lantern", "blanket", "curtain", "pillow",
    "candle", "mirror", "carpet", "ribbon", "basket", "anchor", "compass",
    "trumpet", "violin", "hammer", "shovel", "ladder", "barrel", "wagon",
    "feather", "pebble", "crystal", "shadow", "whisper", "silence",
    "thunder", "breeze", "rainbow", "sunset", "horizon", "twilight",
    "promise", "secret", "memory", "fortune", "mystery", "journey",
    "creature", "phantom", "spirit", "legend", "victory", "treasure",
    "harvest", "shelter", "passage", "kingdom", "empire", "chamber",
    "surface", "pattern", "signal", "method", "reason", "problem",
    "answer", "moment", "feeling", "opinion", "message", "purpose",
    "weather", "season", "morning", "evening", "century", "chapter",
    "balcony", "terrace", "corridor", "cellar", "attic", "workshop",
    "cathedral", "fortress", "pavilion", "monument", "sculpture", "tapestry",
    "garment", "pendant", "artifact", "envelope", "document", "calendar",
    "uniform", "chimney", "stairway", "gateway", "archway", "doorway",
    "musician", "detective", "professor", "commander", "inspector", "inventor",
    "pioneer", "ancestor", "waterfall", "cavern", "lagoon", "prairie",
    "woodland", "hillside", "thicket", "clearing", "ambition", "courage",
    "patience", "wisdom", "sorrow", "triumph", "conflict", "harmony",
    "spectacle", "interval", "boundary", "obstacle", "companion", "remnant",
    "district", "province", "mansion", "council", "carriage", "riddle",
    "marvel", "burden", "emblem", "menace", "doctrine", "essence",
    "counsel", "turmoil", "platform", "fragment", "notion", "symbol",
    "frontier", "outlook", "prospect", "downfall", "legacy", "virtue",
    "tempest", "dungeon", "summit", "refuge", "banner", "cloister",
    # ── expanded ──
    "alcove", "alloy", "anthem", "anvil", "arcade", "arena", "ballot",
    "bastion", "beacon", "belfry", "bellows", "bivouac", "bolster",
    "bramble", "brewer", "brigand", "brooch", "buckle", "bulwark",
    "canal", "canopy", "casket", "cauldron", "cavern", "cinder",
    "citadel", "cobbler", "column", "contour", "crescent", "crevice",
    "crucible", "cypress", "dagger", "decree", "depot", "dialect",
    "ember", "enclave", "ensign", "escort", "falcon", "fissure",
    "fjord", "flannel", "foundry", "frigate", "furrow", "gallows",
    "garland", "garrison", "gazette", "goblet", "granite", "grotto",
    "gully", "gunwale", "halcyon", "hamlet", "harbor", "hearth",
    "herald", "hermit", "heirloom", "hillock", "hollow", "hymnal",
    "incline", "inlet", "insignia", "ivory", "jasmine", "jetty",
    "juniper", "kennel", "kinship", "lancet", "lattice", "laurel",
    "ledger", "linen", "lintel", "maiden", "mantle", "marrow",
    "minstrel", "mirage", "morsel", "mosaic", "parcel", "parish",
    "pasture", "peddler", "pelican", "pennant", "petal", "pilgrim",
    "platter", "plunder", "portico", "quarry", "rampart", "raptor",
    "ravine", "relic", "reverie", "rubble", "sapling", "satchel",
    "scalpel", "schooner", "scourge", "sentinel", "serpent", "shingle",
    "quarrel", "quiver", "ramble", "sandal", "scepter", "spindle",
    "stallion", "steward", "surplus", "talisman", "tendril", "terrace",
    "thistle", "timber", "tinker", "torrent", "trellis", "trinket",
    "turret", "vagrant", "velvet", "venture", "verdict", "vessel",
    "vintage", "warrant", "warden", "willow", "zenith",
]

NOUNS_HARD = [
    "labyrinth", "silhouette", "archipelago", "chandelier", "protagonist",
    "manuscript", "phenomenon", "hemisphere", "catastrophe", "bureaucracy",
    "surveillance", "renaissance", "melancholy", "philosophy", "controversy",
    "temperament", "consequence", "predicament", "architecture", "atmosphere",
    "equilibrium", "paradox", "metaphor", "hypothesis", "rhetoric",
    "algorithm", "infrastructure", "sovereignty", "aristocracy", "expedition",
    "observatory", "constellation", "jurisdiction", "predecessor", "beneficiary",
    "connoisseur", "entrepreneur", "acquaintance", "correspondent",
    "accomplishment", "circumstance", "reconnaissance", "discrepancy",
    "idiosyncrasy", "kaleidoscope", "paraphernalia", "quintessence",
    "anachronism", "juxtaposition", "dichotomy", "epitome", "paradigm",
    "pedagogy", "hierarchy", "cacophony", "soliloquy", "epiphany",
    "metamorphosis", "nomenclature", "perseverance", "serendipity",
    "anthropology", "bibliography", "chronology", "cosmopolitan",
    "deterioration", "magnanimity", "proclivity", "vicissitude",
    "machination", "conflagration", "jurisprudence", "antithesis",
    "catharsis", "diaspora", "hegemony", "synthesis", "symposium",
    "meritocracy", "incandescence", "effervescence",
    # ── expanded ──
    "amalgamation", "benevolence", "bureaucrat", "cartography",
    "clairvoyance", "compendium", "confectionery", "conglomerate",
    "deterioration", "ecclesiastical", "encyclopedia", "extravagance",
    "hallucination", "impoverishment", "incarceration", "infatuation",
    "insufficiency", "interrogation", "magnification", "miscellaneous",
    "nomenclature", "omnipotence", "pandemonium", "perpetuity",
    "philanthropist", "predominantly", "procrastination", "proprietor",
    "reciprocity", "remuneration", "sanctimonious", "surveillance",
    "temperament", "thoroughfare", "transfiguration", "unprecedented",
    "verisimilitude", "vulnerability", "apprehension", "confiscation",
    "denomination", "embellishment", "fortification", "genealogy",
    "humanitarian", "impersonation", "justification", "legitimacy",
    "manifestation", "oscillation", "predominance", "rehabilitation",
    "stratification", "telegraphy", "unification", "vestibule",
]

# ── nouns (plural) ───────────────────────────────────────────────────────────

NOUNS_PL_EASY = [
    "cats", "dogs", "birds", "trees", "roads", "books", "doors", "walls",
    "rooms", "cups", "hats", "shoes", "bags", "keys", "bells", "boats",
    "cars", "hills", "lakes", "farms", "shops", "towns", "paths", "gates",
    "stars", "rocks", "songs", "games", "toys", "ships", "trains", "clocks",
    "gifts", "cakes", "roses", "seeds", "coins", "drums", "rings", "maps",
    "pages", "signs", "steps", "meals", "dreams", "voices", "stories",
    "clouds", "stones", "plates", "floors", "children", "horses", "foxes",
    "wolves", "mice", "leaves", "nights", "rivers", "colors", "smiles",
    "arms", "legs", "heads", "necks", "feet", "bones", "teeth", "eggs",
    "pies", "nuts", "fields", "streams", "ants", "bees", "owls", "pigs",
    "hens", "crows", "hawks", "forks", "knives", "spoons", "bowls", "pots",
    "pans", "jars", "trays", "caves", "sheds", "fences", "lanes", "trails",
    "rules", "words", "lines", "marks", "notes", "spots", "jobs", "tasks",
    "chains", "wheels", "hooks", "nails", "shelves", "frames", "waves",
    "tides", "vines", "storms", "flames", "branches", "trunks", "beaches",
    "banks", "ports", "benches", "roots", "weeds", "thorns", "pools", "logs",
    "ropes", "shirts", "dresses", "frogs", "ducks", "goats", "flags", "ponds",
    # ── expanded ──
    "arches", "axes", "badges", "barns", "beads", "beams", "belts", "blades",
    "blasts", "blazes", "blocks", "blooms", "bolts", "bonds", "booths",
    "braids", "bricks", "brooks", "brushes", "bulbs", "bumps", "bursts",
    "cabins", "cages", "canes", "capes", "carts", "chests", "clams", "claws",
    "cliffs", "cloths", "colts", "combs", "cones", "cords", "corks", "cracks",
    "cranes", "crates", "crests", "crops", "crowns", "crusts", "curls",
    "dents", "ditches", "docks", "domes", "doves", "drains", "drifts",
    "elms", "fawns", "feasts", "figs", "fists", "flocks", "folds", "forges",
    "forts", "glens", "globes", "gloves", "gorges", "grapes", "grips",
    "groves", "gulfs", "gusts", "hares", "harps", "heaps", "hedges", "herbs",
    "herds", "hives", "hoods", "hoops", "horns", "hounds", "huts", "jaws",
    "jewels", "knots", "laces", "ledges", "lids", "limes", "lodges", "lofts",
    "lumps", "manes", "masks", "masts", "mats", "mazes", "mills", "molds",
    "mounds", "mugs", "mules", "oars", "ovens", "palms", "patches", "paws",
    "peaks", "piers", "pines", "planks", "plums", "poles", "porches",
    "prisms", "prizes", "pulses", "quills", "rafts", "ramps", "ravens",
    "reeds", "reefs", "ridges", "roars", "robes", "rods", "roots", "sacks",
    "scars", "scents", "seals", "shafts", "shawls", "slabs", "slopes",
    "slots", "snails", "spans", "sparks", "spears", "spikes", "spools",
    "sprays", "stains", "stakes", "stalks", "stems", "stews", "stools",
    "strands", "straps", "stumps", "thorns", "tiles", "tints", "torches",
    "traps", "trouts", "tusks", "twigs", "veils", "vents", "vows", "wands",
    "wasps", "webs", "wedges", "whips", "wicks", "wreaths", "wrens", "yarns",
    "moths", "notches", "plumes", "pouches", "rifts", "scrolls", "shrubs",
    "skulls", "spires", "sprouts", "stags", "stripes", "surges", "swamps",
    "gems", "dens", "gaps", "growls", "knobs", "moats", "nooks", "oaths",
    "props", "rags", "ruts", "shards", "snags", "snares", "wisps",
]

NOUNS_PL_MEDIUM = [
    "gardens", "villages", "mountains", "libraries", "markets", "temples",
    "castles", "forests", "islands", "valleys", "deserts", "meadows",
    "palaces", "towers", "fountains", "orchards", "glaciers", "soldiers",
    "merchants", "scholars", "strangers", "travelers", "guardians",
    "journals", "portraits", "lanterns", "curtains", "candles", "mirrors",
    "feathers", "crystals", "shadows", "whispers", "promises", "secrets",
    "memories", "mysteries", "journeys", "creatures", "legends", "treasures",
    "kingdoms", "chambers", "surfaces", "patterns", "signals", "reasons",
    "problems", "answers", "moments", "feelings", "opinions", "messages",
    "seasons", "mornings", "evenings", "centuries", "chapters", "victories",
    "balconies", "terraces", "corridors", "cellars", "workshops", "cathedrals",
    "fortresses", "pavilions", "monuments", "sculptures", "tapestries",
    "garments", "artifacts", "envelopes", "documents", "calendars",
    "musicians", "detectives", "professors", "commanders", "inspectors",
    "inventors", "pioneers", "ancestors", "waterfalls", "caverns", "lagoons",
    "prairies", "woodlands", "hillsides", "thickets", "clearings",
    "ambitions", "spectacles", "intervals", "boundaries", "obstacles",
    "companions", "remnants", "districts", "provinces", "mansions",
    "councils", "carriages", "riddles", "marvels", "burdens", "emblems",
    "doctrines", "fragments", "notions", "symbols", "frontiers", "prospects",
    "legacies", "virtues", "tempests", "dungeons", "summits", "refuges",
    "banners",
    # ── expanded ──
    "alcoves", "alloys", "anthems", "anvils", "arcades", "arenas", "ballots",
    "bastions", "beacons", "bellows", "brambles", "brooches", "buckles",
    "canals", "canopies", "caskets", "cauldrons", "cinders", "citadels",
    "cobblers", "columns", "contours", "crescents", "crevices", "crucibles",
    "daggers", "decrees", "depots", "dialects", "embers", "enclaves",
    "escorts", "falcons", "fissures", "foundries", "frigates", "furrows",
    "garlands", "garrisons", "gazettes", "goblets", "grottos", "gullies",
    "hamlets", "harbors", "hearths", "heralds", "hermits", "heirlooms",
    "hillocks", "hollows", "hymns", "inclines", "inlets", "jasmines",
    "jetties", "junipers", "kennels", "lancets", "lattices", "laurels",
    "ledgers", "linens", "lintels", "maidens", "mantles", "minstrels",
    "mirages", "morsels", "mosaics", "parcels", "parishes", "pastures",
    "peddlers", "pelicans", "pennants", "petals", "pilgrims", "platters",
    "porticos", "quarries", "ramparts", "raptors", "ravines", "relics",
    "reveries", "saplings", "satchels", "schooners", "sentinels", "serpents",
    "shingles", "quivers", "sandals", "scepters", "spindles", "stallions",
    "stewards", "talismans", "tendrils", "terraces", "thistles", "tinkers",
    "torrents", "trellises", "trinkets", "turrets", "vagrants", "ventures",
    "verdicts", "vessels", "vintages", "wardens", "willows",
]

NOUNS_PL_HARD = [
    "labyrinths", "silhouettes", "manuscripts", "catastrophes", "phenomena",
    "hemispheres", "consequences", "predicaments", "atmospheres", "paradoxes",
    "metaphors", "hypotheses", "algorithms", "expeditions", "constellations",
    "accomplishments", "circumstances", "discrepancies", "kaleidoscopes",
    "anachronisms", "juxtapositions", "dichotomies", "epitomes", "paradigms",
    "hierarchies", "soliloquies", "epiphanies", "metamorphoses",
    "bibliographies", "vicissitudes", "machinations", "conflagrations",
    "antitheses", "diasporas", "symposia", "transgressions", "proclivities",
    "syntheses", "deteriorations", "idiosyncrasies",
    # ── expanded ──
    "amalgamations", "appendages", "bureaucracies", "cartographies",
    "compendiums", "conglomerates", "encyclopedias", "extravagances",
    "hallucinations", "incarcerations", "infatuations", "interrogations",
    "magnifications", "pandemoniums", "perpetuities", "philanthropists",
    "proprietors", "reciprocities", "remunerations", "thoroughfares",
    "transfigurations", "verisimilitudes", "vulnerabilities",
    "apprehensions", "confiscations", "denominations", "embellishments",
    "fortifications", "genealogies", "justifications", "manifestations",
    "oscillations", "rehabilitations", "stratifications", "vestibules",
]

# ── proper names ─────────────────────────────────────────────────────────────

NAMES = [
    "Alice", "James", "Clara", "Henry", "Elena", "Thomas", "Sarah", "Oliver",
    "Grace", "William", "Emma", "Daniel", "Sophie", "Marcus", "Violet",
    "Arthur", "Helen", "George", "Anna", "Edward", "Maria", "Charles",
    "Rose", "Peter", "Julia", "Samuel", "Lucy", "David", "Margaret",
    "Robert", "Eleanor", "Frank", "Ruth", "Leon", "Ada", "Felix",
    "Iris", "Hugo", "Vera", "Max", "Nora", "Paul", "Lily", "Oscar",
    "June", "Miles", "Ella", "Simon", "Jane", "Victor", "Eve", "Martin",
    "Hazel", "Albert", "Ivy", "Louis", "Alma", "Walter", "Flora", "Leo",
    "Philip", "Raymond", "Harold", "Bernard", "Lionel", "Edmund", "Roland",
    "Conrad", "Martha", "Agnes", "Edith", "Pearl", "Mabel", "Cora",
    "Estelle", "Lydia", "Calvin", "Ernest", "Gilbert", "Warren", "Lena",
    "Owen", "Cecil", "Wilma", "Faye", "Seth", "Nina", "Karl", "Greta",
    "Anton", "Stella", "Milo", "Naomi", "Basil", "Petra", "Robin",
    "Claude", "Maude", "Rex",
    # ── expanded ──
    "Abigail", "Amelia", "Beatrice", "Bridget", "Camille", "Caroline",
    "Charlotte", "Daphne", "Diana", "Dorothy", "Ellen", "Evelyn",
    "Florence", "Frances", "Genevieve", "Gloria", "Hannah", "Harriet",
    "Ingrid", "Isabelle", "Josephine", "Katherine", "Lenore", "Lillian",
    "Louisa", "Madeline", "Marion", "Miriam", "Nadine", "Nellie",
    "Olympia", "Penelope", "Priscilla", "Rachel", "Rebecca", "Rosalind",
    "Sylvia", "Teresa", "Theresa", "Vivian", "Winifred",
    "Abraham", "Alfred", "Benedict", "Clement", "Desmond", "Douglas",
    "Edwin", "Elliot", "Francis", "Frederick", "Gerald", "Gordon",
    "Harvey", "Herbert", "Irving", "Jerome", "Kenneth", "Lawrence",
    "Leonard", "Malcolm", "Nathaniel", "Norbert", "Patrick", "Quentin",
    "Reginald", "Rupert", "Stanley", "Sterling", "Theodore", "Vincent",
    "Wallace", "Winston", "Alistair", "Bartholomew", "Cornelius",
    "Emmett", "Jasper", "Lester", "Morton", "Percival", "Randolph",
    "Silas", "Tobias", "Vernon", "Wesley", "Wyatt",
]

# ── verbs (past tense) ──────────────────────────────────────────────────────

VERBS_PAST_EASY = [
    "saw", "ran", "sat", "ate", "had", "got", "put", "let", "cut", "hit",
    "set", "won", "led", "met", "held", "told", "read", "kept", "gave",
    "took", "came", "made", "went", "said", "knew", "felt", "left", "found",
    "lost", "heard", "paid", "sent", "fell", "drew", "grew", "hung", "laid",
    "rode", "rose", "sang", "sank", "shut", "slid", "sold", "wore", "woke",
    "liked", "loved", "hoped", "moved", "used", "lived", "played", "asked",
    "tried", "walked", "looked", "turned", "called", "needed", "worked",
    "pulled", "picked", "pushed", "dropped", "washed", "filled", "saved",
    "bit", "dug", "fed", "flew", "hid", "blew", "broke", "built",
    "burned", "bought", "brought", "caught", "chose", "drank", "drove",
    "fought", "forgot", "froze", "jumped", "kicked", "kissed", "knocked",
    "laughed", "learned", "lifted", "missed", "named", "passed", "prayed",
    "rained", "rubbed", "rushed", "served", "shaped", "shared", "showed",
    "slept", "smiled", "spoke", "stood", "stopped", "swept", "swam",
    "swore", "threw", "tied", "touched", "waved", "wished", "yelled",
    "aimed", "begged", "blessed", "bowed", "clapped", "crawled", "cried",
    "danced",
    # ── expanded ──
    "bent", "bore", "bound", "carved", "chased", "clasped", "cleaned",
    "climbed", "clung", "cooked", "counted", "crept", "crushed", "cursed",
    "dared", "dimmed", "dipped", "dragged", "dried", "earned", "ended",
    "faded", "feared", "fixed", "flipped", "floated", "folded", "formed",
    "frowned", "gained", "gasped", "gazed", "grabbed", "groaned", "guessed",
    "handled", "harmed", "healed", "heated", "hummed", "hunted", "hurled",
    "inked", "jammed", "joined", "judged", "landed", "lasted", "leaned",
    "leapt", "licked", "limped", "loaded", "locked", "logged", "looped",
    "marked", "marched", "mended", "mixed", "moaned", "nailed", "nodded",
    "obeyed", "packed", "parked", "patched", "paused", "peeled", "pinched",
    "pitched", "placed", "planned", "pleased", "plucked", "pointed",
    "poured", "praised", "pressed", "printed", "probed", "proved",
    "pumped", "punched", "raised", "rapped", "reached", "rested", "ripped",
    "roamed", "rolled", "rotted", "rubbed", "ruled", "sailed", "scraped",
    "sealed", "searched", "seized", "shaved", "shifted", "shipped",
    "sighed", "signed", "sipped", "slammed", "slapped", "sliced",
    "slipped", "smashed", "smelled", "snapped", "soaked", "solved",
    "sorted", "sparked", "spelled", "spilled", "spun", "squeezed",
    "stacked", "staged", "stamped", "stared", "starved", "steered",
    "stirred", "stored", "stripped", "stroked", "stuffed", "swayed",
    "tapped", "tasted", "teased", "thanked", "traced", "traded",
    "trapped", "trembled", "tricked", "trimmed", "trusted", "tumbled",
    "twisted", "typed", "urged", "vowed", "wandered", "warned", "wasted",
    "weighed", "welcomed", "whipped", "whispered", "wounded", "wrapped",
    "yanked", "yawned", "yielded",
]

VERBS_PAST_MEDIUM = [
    "opened", "closed", "carried", "studied", "noticed", "watched",
    "reached", "crossed", "entered", "climbed", "planted", "painted",
    "gathered", "offered", "promised", "believed", "whispered", "wandered",
    "returned", "followed", "finished", "covered", "searched", "removed",
    "decided", "expected", "answered", "demanded", "explored", "imagined",
    "measured", "observed", "prepared", "repeated", "revealed", "selected",
    "shattered", "balanced", "captured", "defended", "escaped", "fastened",
    "honored", "inspired", "launched", "mastered", "polished", "recalled",
    "rescued", "scattered", "trembled", "troubled", "vanished", "welcomed",
    "arranged", "borrowed", "composed", "discovered", "embraced", "examined",
    "traveled", "delivered", "abandoned", "collected", "destroyed", "survived",
    "absorbed", "achieved", "admired", "advanced", "altered", "appeared",
    "assembled", "attached", "attempted", "avoided", "beckoned", "bordered",
    "celebrated", "challenged", "circled", "commanded", "compared", "completed",
    "concealed", "condemned", "confirmed", "connected", "conquered", "convinced",
    "corrected", "created", "darkened", "departed", "described", "designed",
    "detected", "directed", "disturbed", "divided", "elevated", "emerged",
    "employed", "enclosed", "endured", "engaged", "enriched", "envisioned",
    "established", "exhausted", "expanded", "fashioned", "flickered",
    "flourished", "focused", "fractured", "fumbled", "harbored", "hesitated",
    "hindered", "lingered", "marveled", "mentioned", "mourned",
    # ── expanded ──
    "accomplished", "acquired", "addressed", "adjusted", "afforded",
    "allocated", "amended", "announced", "applauded", "appointed",
    "approached", "approved", "assaulted", "bargained", "bewildered",
    "blossomed", "bothered", "broadened", "burdened", "canceled",
    "cautioned", "cherished", "circulated", "comforted", "committed",
    "communicated", "compelled", "compiled", "complained", "compressed",
    "concealed", "concluded", "conducted", "confessed", "confined",
    "confronted", "consented", "conserved", "constructed", "consulted",
    "consumed", "contracted", "converted", "cooperated", "counseled",
    "cultivated", "curtailed", "decorated", "deflected", "delighted",
    "demolished", "descended", "determined", "devoured", "diminished",
    "discarded", "disguised", "dismissed", "dispatched", "displaced",
    "dissolved", "dominated", "eliminated", "embarked", "embodied",
    "emphasized", "encountered", "encouraged", "engineered", "enlightened",
    "entertained", "enveloped", "evaluated", "excavated", "exchanged",
    "exclaimed", "exercised", "exploited", "extracted", "fermented",
    "formulated", "fractured", "frightened", "fulfilled", "furnished",
    "generated", "graduated", "guaranteed", "harvested", "hastened",
    "illustrated", "immersed", "implemented", "impressed", "increased",
    "indicated", "inflicted", "inhabited", "inherited", "instructed",
    "interpreted", "introduced", "journeyed", "justified", "navigated",
    "neglected", "negotiated", "nourished", "objected", "occupied",
    "organized", "outweighed", "overlooked", "penetrated", "permitted",
    "persuaded", "pioneered", "positioned", "predicted", "prevented",
    "proceeded", "processed", "produced", "projected", "prolonged",
    "promoted", "prospered", "protected", "protested", "published",
    "purchased", "questioned", "reassured", "recovered", "reflected",
    "reformed", "registered", "regulated", "reinforced", "rejected",
    "relinquished", "remembered", "resembled", "responded", "restored",
    "restricted", "retreated", "sacrificed", "sanctioned", "sharpened",
    "sheltered", "shouldered", "silenced", "simplified", "slaughtered",
    "smothered", "solicited", "speculated", "staggered", "stimulated",
    "struggled", "submitted", "succeeded", "suggested", "supported",
    "suppressed", "surrounded", "suspended", "swallowed", "thundered",
    "tolerated", "tormented", "transformed", "transported", "trespassed",
    "triumphed", "undermined", "unfastened", "unraveled", "ventured",
    "volunteered", "weathered", "witnessed", "wondered", "worshipped",
]

VERBS_PAST_HARD = [
    "acknowledged", "accompanied", "administered", "anticipated", "approximated",
    "articulated", "characterized", "commemorated", "comprehended", "concentrated",
    "consolidated", "contemplated", "contributed", "deliberated", "deteriorated",
    "distinguished", "endeavored", "exaggerated", "extinguished", "facilitated",
    "illuminated", "inaugurated", "manipulated", "necessitated", "orchestrated",
    "overwhelmed", "persevered", "proliferated", "rationalized", "reverberated",
    "scrutinized", "surrendered", "sympathized", "transcended", "underestimated",
    "accommodated", "adjudicated", "amalgamated", "authenticated", "capitulated",
    "circumnavigated", "conceptualized", "corroborated", "disillusioned",
    "disseminated", "extrapolated", "hallucinated", "hypothesized",
    "incapacitated", "interrogated", "miscalculated", "overcompensated",
    "procrastinated", "rehabilitated", "substantiated", "predominated",
    "communicated", "differentiated", "impersonated", "investigated",
    # ── expanded ──
    "appropriated", "confiscated", "decapitated", "domesticated",
    "ecclesiasticated", "exacerbated", "gesticulated", "hallucinated",
    "illuminated", "incriminated", "juxtaposed", "legitimized",
    "misappropriated", "overestimated", "pontificated", "reconnoitered",
    "repudiated", "sequestered", "transubstantiated", "underrepresented",
    "venerated", "vociferated", "disenfranchised", "excommunicated",
    "hyperventilated", "institutionalized", "maladministered",
    "overcompensated", "presupposed", "unaccompanied",
]

# ── verbs (3rd person present) ───────────────────────────────────────────────

VERBS_PRES_EASY = [
    "sees", "runs", "sits", "eats", "gets", "puts", "lets", "cuts", "hits",
    "sets", "wins", "leads", "meets", "holds", "tells", "reads", "keeps",
    "gives", "takes", "comes", "makes", "goes", "says", "knows", "feels",
    "finds", "hears", "pays", "sends", "falls", "draws", "grows", "rides",
    "sings", "shuts", "sells", "wears", "likes", "loves", "hopes", "moves",
    "uses", "lives", "plays", "asks", "tries", "walks", "looks", "turns",
    "calls", "needs", "works", "pulls", "picks", "drops", "fills", "saves",
    "bites", "digs", "feeds", "flies", "hides", "blows", "breaks", "builds",
    "burns", "buys", "brings", "catches", "drinks", "drives", "fights",
    "forgets", "freezes", "jumps", "kicks", "knocks", "laughs", "learns",
    "lifts", "misses", "names", "passes", "rains", "rushes", "serves",
    "shapes", "shares", "shows", "sleeps", "smiles", "speaks", "stands",
    "stops", "sweeps", "swims", "throws", "ties", "touches", "waves",
    # ── expanded ──
    "bends", "binds", "carves", "chases", "cleans", "clings", "cooks",
    "counts", "creeps", "crushes", "dares", "dips", "drags", "dries",
    "earns", "ends", "fades", "fears", "fixes", "flips", "floats",
    "folds", "forms", "frowns", "gains", "gasps", "gazes", "grabs",
    "groans", "guesses", "handles", "harms", "heals", "heats", "hums",
    "hunts", "hurls", "jams", "joins", "judges", "lands", "lasts",
    "leans", "leaps", "licks", "limps", "loads", "locks", "loops",
    "marks", "marches", "mends", "mixes", "moans", "nails", "nods",
    "obeys", "packs", "patches", "pauses", "peels", "pinches", "places",
    "plans", "pleases", "plucks", "points", "pours", "praises", "presses",
    "prints", "probes", "proves", "pumps", "punches", "raises", "rests",
    "rips", "roams", "rolls", "rules", "sails", "scrapes", "seals",
    "seizes", "shifts", "sighs", "signs", "sips", "slams", "slaps",
    "slices", "slips", "smashes", "smells", "snaps", "soaks", "solves",
    "sorts", "sparks", "spells", "spills", "spins", "squeezes", "stacks",
    "stamps", "stares", "steers", "stirs", "stores", "strokes", "stuffs",
    "sways", "taps", "tastes", "teases", "thanks", "traces", "trades",
    "traps", "tricks", "trims", "trusts", "tumbles", "twists", "types",
    "urges", "vows", "warns", "wastes", "weighs", "whips", "whispers",
    "wraps", "yanks", "yawns", "yields",
]

VERBS_PRES_MEDIUM = [
    "opens", "closes", "carries", "studies", "notices", "watches",
    "reaches", "crosses", "enters", "climbs", "gathers", "offers",
    "promises", "believes", "whispers", "wanders", "returns", "follows",
    "finishes", "covers", "searches", "removes", "decides", "expects",
    "answers", "demands", "explores", "imagines", "measures", "observes",
    "prepares", "repeats", "reveals", "selects", "captures", "defends",
    "escapes", "inspires", "launches", "polishes", "recalls", "rescues",
    "scatters", "trembles", "vanishes", "welcomes", "arranges", "composes",
    "discovers", "examines", "embraces", "delivers", "collects", "survives",
    "absorbs", "achieves", "admires", "advances", "alters", "appears",
    "assembles", "attaches", "attempts", "avoids", "beckons", "borders",
    "celebrates", "challenges", "circles", "commands", "compares", "completes",
    "conceals", "condemns", "confirms", "connects", "conquers", "convinces",
    "corrects", "creates", "darkens", "departs", "describes", "designs",
    "detects", "directs", "disturbs", "divides", "elevates", "emerges",
    "employs", "encloses", "endures", "engages", "enriches", "envisions",
    "establishes", "exhausts", "expands", "fashions", "flickers", "flourishes",
    # ── expanded ──
    "accomplishes", "acquires", "adjusts", "affords", "allocates", "amends",
    "announces", "applauds", "approaches", "approves", "bargains", "bewilders",
    "blossoms", "bothers", "broadens", "burdens", "cautions", "cherishes",
    "circulates", "comforts", "commits", "compels", "compiles", "complains",
    "compresses", "conceals", "concludes", "conducts", "confesses", "confines",
    "confronts", "consents", "conserves", "constructs", "consults", "consumes",
    "converts", "cooperates", "counsels", "cultivates", "decorates", "deflects",
    "delights", "demolishes", "descends", "determines", "devours", "diminishes",
    "discards", "disguises", "dismisses", "dispatches", "displaces", "dissolves",
    "dominates", "eliminates", "embarks", "embodies", "emphasizes", "encounters",
    "encourages", "engineers", "enlightens", "entertains", "evaluates",
    "exchanges", "exclaims", "exercises", "exploits", "extracts", "formulates",
    "frightens", "fulfills", "furnishes", "generates", "graduates", "guarantees",
    "harvests", "hastens", "illustrates", "immerses", "implements", "impresses",
    "increases", "indicates", "inflicts", "inhabits", "inherits", "instructs",
    "interprets", "introduces", "justifies", "navigates", "neglects",
    "negotiates", "nourishes", "occupies", "organizes", "overlooks", "penetrates",
    "permits", "persuades", "pioneers", "positions", "predicts", "prevents",
    "proceeds", "processes", "produces", "projects", "prolongs", "promotes",
    "prospers", "protects", "protests", "publishes", "purchases", "questions",
    "reassures", "recovers", "reflects", "reforms", "registers", "regulates",
    "reinforces", "rejects", "remembers", "resembles", "responds", "restores",
    "restricts", "retreats", "sacrifices", "sanctions", "sharpens", "shelters",
    "silences", "simplifies", "solicits", "speculates", "staggers", "stimulates",
    "struggles", "submits", "succeeds", "suggests", "supports", "suppresses",
    "surrounds", "suspends", "swallows", "thunders", "tolerates", "transforms",
    "transports", "trespasses", "triumphs", "undermines", "unravels", "ventures",
    "volunteers", "weathers", "witnesses", "wonders", "worships",
]

# ── verbs (base/infinitive) ─────────────────────────────────────────────────

VERBS_BASE_EASY = [
    "see", "run", "sit", "eat", "get", "put", "let", "cut", "hit", "set",
    "win", "lead", "meet", "hold", "tell", "read", "keep", "give", "take",
    "come", "make", "go", "say", "know", "feel", "find", "hear", "pay",
    "send", "fall", "draw", "grow", "ride", "sing", "shut", "sell", "wear",
    "like", "love", "hope", "move", "use", "live", "play", "ask", "try",
    "walk", "look", "turn", "call", "need", "work", "pull", "pick", "drop",
    "fill", "save", "rest", "wait", "help", "pass", "stay", "hide", "swim",
    "bite", "dig", "feed", "fly", "blow", "break", "build", "burn",
    "buy", "bring", "catch", "choose", "drink", "drive", "fight", "forget",
    "freeze", "jump", "kick", "kiss", "knock", "laugh", "learn", "lift",
    "miss", "name", "pray", "rain", "rub", "rush", "serve", "shape",
    "share", "show", "sleep", "smile", "speak", "stand", "stop", "sweep",
    "swear", "throw", "tie", "touch", "wave", "wish", "aim", "beg",
    "bless", "bow", "clap", "crawl", "cry", "dance", "yell",
    # ── expanded ──
    "bend", "bind", "carve", "chase", "clean", "cling", "cook", "count",
    "creep", "crush", "dare", "dip", "drag", "drift", "dry", "earn",
    "end", "fade", "fear", "fix", "flip", "float", "fold", "form",
    "frown", "gain", "gasp", "gaze", "grab", "groan", "guess", "handle",
    "harm", "heal", "heat", "hum", "hunt", "hurl", "jam", "join",
    "judge", "land", "last", "lean", "leap", "lick", "load", "lock",
    "loop", "mend", "mix", "moan", "nail", "nod", "obey", "pack",
    "patch", "pause", "peel", "pinch", "pitch", "place", "plan",
    "please", "pluck", "point", "pour", "praise", "press", "print",
    "probe", "prove", "pump", "punch", "raise", "rip", "roam", "roll",
    "sail", "scrape", "seal", "seize", "shift", "sigh", "sign", "sip",
    "slam", "slap", "slice", "slip", "smash", "smell", "snap", "soak",
    "solve", "sort", "spark", "spell", "spill", "spin", "squeeze",
    "stack", "stamp", "stare", "steer", "stir", "store", "stroke",
    "stuff", "sway", "tap", "taste", "tease", "thank", "trace", "trade",
    "trap", "trick", "trust", "tumble", "twist", "type", "urge",
    "warn", "waste", "weigh", "whip", "wrap", "yank", "yield",
]

VERBS_BASE_MEDIUM = [
    "open", "close", "carry", "study", "notice", "watch", "reach", "cross",
    "enter", "climb", "gather", "offer", "promise", "believe", "whisper",
    "wander", "return", "follow", "finish", "cover", "search", "remove",
    "decide", "expect", "answer", "demand", "explore", "imagine", "measure",
    "observe", "prepare", "repeat", "reveal", "select", "capture", "defend",
    "escape", "inspire", "launch", "polish", "recall", "rescue", "scatter",
    "tremble", "vanish", "welcome", "arrange", "compose", "discover",
    "examine", "embrace", "deliver", "collect", "survive", "approach",
    "consider", "establish", "maintain", "remember", "understand", "continue",
    "absorb", "achieve", "admire", "advance", "alter", "appear",
    "assemble", "attach", "attempt", "avoid", "beckon", "border",
    "celebrate", "challenge", "circle", "command", "compare", "complete",
    "conceal", "condemn", "confirm", "connect", "conquer", "convince",
    "correct", "create", "darken", "depart", "describe", "design",
    "detect", "direct", "disturb", "divide", "elevate", "emerge",
    "employ", "enclose", "endure", "engage",
    # ── expanded ──
    "accomplish", "acquire", "adjust", "afford", "allocate", "amend",
    "announce", "applaud", "approve", "bargain", "bewilder", "blossom",
    "bother", "broaden", "burden", "caution", "cherish", "circulate",
    "comfort", "commit", "compel", "compile", "complain", "compress",
    "conceal", "conclude", "conduct", "confess", "confine", "confront",
    "consent", "conserve", "construct", "consult", "consume", "convert",
    "cooperate", "counsel", "cultivate", "decorate", "deflect", "delight",
    "demolish", "descend", "determine", "devour", "diminish", "discard",
    "disguise", "dismiss", "dispatch", "displace", "dissolve", "dominate",
    "eliminate", "embark", "embody", "emphasize", "encounter", "encourage",
    "engineer", "enlighten", "entertain", "evaluate", "exchange", "exclaim",
    "exercise", "exploit", "extract", "formulate", "frighten", "fulfill",
    "furnish", "generate", "graduate", "guarantee", "harvest", "hasten",
    "illustrate", "immerse", "implement", "impress", "increase", "indicate",
    "inflict", "inhabit", "inherit", "instruct", "interpret", "introduce",
    "justify", "navigate", "neglect", "negotiate", "nourish", "occupy",
    "organize", "overlook", "penetrate", "permit", "persuade", "pioneer",
    "position", "predict", "prevent", "proceed", "process", "produce",
    "project", "prolong", "promote", "prosper", "protect", "protest",
    "publish", "purchase", "question", "reassure", "recover", "reflect",
    "reform", "register", "regulate", "reinforce", "reject", "resemble",
    "respond", "restore", "restrict", "retreat", "sacrifice", "sanction",
    "sharpen", "shelter", "silence", "simplify", "solicit", "speculate",
    "stagger", "stimulate", "struggle", "submit", "succeed", "suggest",
    "support", "suppress", "surround", "suspend", "swallow", "tolerate",
    "transform", "transport", "trespass", "triumph", "undermine", "unravel",
    "volunteer", "weather", "witness", "wonder", "worship",
]

# ── verbs (gerund / -ing) ───────────────────────────────────────────────────

VERBS_ING_EASY = [
    "running", "sitting", "eating", "getting", "cutting", "hitting",
    "winning", "reading", "keeping", "making", "going", "saying",
    "looking", "walking", "turning", "calling", "working", "playing",
    "trying", "living", "moving", "using", "hoping", "loving",
    "pulling", "picking", "dropping", "filling", "saving", "hiding",
    "waiting", "resting", "helping", "singing", "riding", "drawing",
    "biting", "digging", "feeding", "flying", "blowing", "breaking",
    "building", "burning", "buying", "bringing", "catching", "drinking",
    "driving", "fighting", "jumping", "kicking", "kissing", "knocking",
    "laughing", "learning", "lifting", "missing", "naming", "passing",
    "rushing", "sleeping", "smiling", "speaking", "standing", "stopping",
    "swimming", "throwing", "tying", "waving",
    # ── expanded ──
    "bending", "binding", "carving", "chasing", "cleaning", "clinging",
    "cooking", "counting", "creeping", "crushing", "daring", "dipping",
    "dragging", "drifting", "drying", "earning", "ending", "fading",
    "fearing", "fixing", "flipping", "floating", "folding", "forming",
    "frowning", "gaining", "gasping", "gazing", "grabbing", "groaning",
    "guessing", "handling", "harming", "healing", "heating", "humming",
    "hunting", "hurling", "jamming", "joining", "judging", "landing",
    "lasting", "leaning", "leaping", "licking", "loading", "locking",
    "looping", "marking", "marching", "mending", "mixing", "moaning",
    "nailing", "nodding", "obeying", "packing", "patching", "pausing",
    "peeling", "pinching", "placing", "planning", "pleasing", "plucking",
    "pointing", "pouring", "praising", "pressing", "printing", "probing",
    "proving", "pumping", "punching", "raising", "resting", "ripping",
    "roaming", "rolling", "ruling", "sailing", "scraping", "sealing",
    "seizing", "shifting", "sighing", "signing", "sipping", "slamming",
    "slapping", "slicing", "slipping", "smashing", "smelling", "snapping",
    "soaking", "solving", "sorting", "sparking", "spelling", "spilling",
    "spinning", "squeezing", "stacking", "stamping", "staring", "steering",
    "stirring", "storing", "stroking", "stuffing", "swaying", "tapping",
    "tasting", "teasing", "thanking", "tracing", "trading", "trapping",
    "tricking", "trimming", "trusting", "tumbling", "twisting", "typing",
    "urging", "vowing", "warning", "wasting", "weighing", "whipping",
    "wrapping", "yanking", "yawning", "yielding",
]

VERBS_ING_MEDIUM = [
    "opening", "closing", "carrying", "studying", "watching", "climbing",
    "reaching", "crossing", "entering", "gathering", "offering", "believing",
    "whispering", "wandering", "returning", "following", "finishing",
    "covering", "searching", "removing", "deciding", "expecting",
    "answering", "demanding", "exploring", "imagining", "measuring",
    "observing", "preparing", "repeating", "revealing", "selecting",
    "capturing", "defending", "escaping", "inspiring", "polishing",
    "recalling", "rescuing", "trembling", "vanishing", "arranging",
    "composing", "discovering", "examining", "embracing", "delivering",
    "absorbing", "achieving", "admiring", "advancing", "altering",
    "appearing", "assembling", "attaching", "attempting", "avoiding",
    "beckoning", "bordering", "celebrating", "challenging", "circling",
    "commanding", "comparing", "completing", "concealing", "condemning",
    "confirming", "connecting", "conquering", "convincing", "correcting",
    "creating", "darkening", "departing", "describing", "designing",
    "detecting", "directing", "disturbing", "dividing", "elevating",
    "emerging", "employing", "enclosing", "enduring", "engaging",
    "enriching", "envisioning", "expanding",
    # ── expanded ──
    "accomplishing", "acquiring", "adjusting", "affording", "allocating",
    "amending", "announcing", "applauding", "approaching", "approving",
    "bargaining", "bewildering", "blossoming", "bothering", "broadening",
    "burdening", "cautioning", "cherishing", "circulating", "comforting",
    "committing", "compelling", "compiling", "complaining", "compressing",
    "concealing", "concluding", "conducting", "confessing", "confining",
    "confronting", "consenting", "conserving", "constructing", "consulting",
    "consuming", "converting", "cooperating", "counseling", "cultivating",
    "decorating", "deflecting", "delighting", "demolishing", "descending",
    "determining", "devouring", "diminishing", "discarding", "disguising",
    "dismissing", "dispatching", "displacing", "dissolving", "dominating",
    "eliminating", "embarking", "embodying", "emphasizing", "encountering",
    "encouraging", "engineering", "enlightening", "entertaining", "evaluating",
    "exchanging", "exclaiming", "exercising", "exploiting", "extracting",
    "formulating", "frightening", "fulfilling", "furnishing", "generating",
    "graduating", "guaranteeing", "harvesting", "hastening", "illustrating",
    "immersing", "implementing", "impressing", "increasing", "indicating",
    "inflicting", "inhabiting", "inheriting", "instructing", "interpreting",
    "introducing", "justifying", "navigating", "neglecting", "negotiating",
    "nourishing", "occupying", "organizing", "overlooking", "penetrating",
    "permitting", "persuading", "pioneering", "positioning", "predicting",
    "preventing", "processing", "producing", "projecting", "prolonging",
    "promoting", "prospering", "protecting", "protesting", "publishing",
    "purchasing", "questioning", "reassuring", "recovering", "reflecting",
    "reforming", "registering", "regulating", "reinforcing", "rejecting",
    "resembling", "responding", "restoring", "restricting", "retreating",
    "sacrificing", "sanctioning", "sharpening", "sheltering", "silencing",
    "simplifying", "soliciting", "speculating", "staggering", "stimulating",
    "struggling", "submitting", "succeeding", "suggesting", "supporting",
    "suppressing", "surrounding", "suspending", "swallowing", "tolerating",
    "transforming", "transporting", "trespassing", "triumphing", "undermining",
    "unraveling", "volunteering", "weathering", "witnessing", "wondering",
]

# ── adjectives ───────────────────────────────────────────────────────────────

ADJ_EASY = [
    "big", "small", "old", "new", "long", "short", "tall", "wide", "thin",
    "fast", "slow", "hot", "cold", "warm", "cool", "soft", "hard", "dark",
    "bright", "clean", "dry", "wet", "flat", "deep", "high", "low", "full",
    "empty", "rich", "poor", "kind", "fair", "safe", "wild", "calm", "bold",
    "glad", "sad", "lost", "free", "real", "true", "good", "bad", "nice",
    "fine", "red", "blue", "green", "white", "black", "gray", "brown",
    "pale", "round", "sharp", "plain", "fresh", "clear", "sweet", "young",
    "quiet", "loud", "strong", "weak", "quick", "rare", "late", "early",
    "rough", "smooth", "thick", "tight", "loose", "dull", "odd", "neat",
    "sick", "bare", "blind", "brief", "broad", "cheap", "cruel", "dense",
    "dim", "fierce", "firm", "fit", "fond", "foul", "grim", "harsh",
    "keen", "lame", "lean", "mad", "mere", "mild", "mute", "numb",
    "pink", "proud", "pure", "ripe", "rude", "shy", "slight", "slim",
    "smart", "sore", "stiff", "strict", "tense", "tough", "vast", "wise",
    "worn", "blunt", "coarse", "crisp", "cute", "deaf", "faint", "false",
    "grand", "grave", "gross", "limp", "lone", "steep", "stale", "stern",
    # ── expanded ──
    "bleak", "brash", "brisk", "coy", "drab", "dread", "drear", "dusk",
    "edgy", "eerie", "faded", "fervent", "frail", "gaunt", "ghastly",
    "giddy", "glum", "gory", "gruff", "hefty", "hoarse", "icy", "idle",
    "jarring", "jolly", "lavish", "lofty", "meek", "mellow", "murky",
    "musty", "naive", "nimble", "opaque", "plush", "prim", "quaint",
    "raw", "rigid", "rosy", "rusty", "shaky", "sheer", "sleek", "snug",
    "somber", "sparse", "stark", "stocky", "stout", "stuffy", "supple",
    "tame", "tart", "tepid", "timid", "toxic", "trim", "trivial",
    "vain", "vivid", "wary", "weary", "witty", "wobbly", "wry",
    "zesty", "agile", "azure", "bland", "breezy", "chilly", "cozy",
    "crispy", "curly", "dingy", "dizzy", "dreary", "dusky", "dusty",
    "feisty", "flimsy", "fluffy", "foggy", "fuzzy", "gloomy", "grimy",
    "gritty", "grubby", "hazy", "husky", "jumpy", "lanky", "lumpy",
    "messy", "misty", "moody", "mossy", "muddy", "peppy", "perky",
    "plump", "raspy", "rocky", "sandy", "salty", "scruffy", "shaggy",
    "silky", "slimy", "smoky", "soggy", "stormy", "stuffy", "sunny",
    "swampy", "tangy", "tasty", "thorny", "toasty", "tricky", "twitchy",
    "wacky", "whiny", "windy", "woolly", "zippy",
]

ADJ_MEDIUM = [
    "gentle", "bitter", "golden", "silver", "hollow", "narrow", "frozen",
    "hidden", "broken", "silent", "ancient", "modern", "distant", "curious",
    "careful", "fearful", "grateful", "honest", "humble", "clever", "proper",
    "sudden", "formal", "simple", "steady", "subtle", "elegant", "fragile",
    "massive", "patient", "private", "sacred", "strange", "typical", "urgent",
    "useful", "violent", "visible", "willing", "worried", "familiar",
    "peaceful", "powerful", "pleasant", "splendid", "terrible", "fortunate",
    "important", "beautiful", "dangerous", "difficult", "delicate", "graceful",
    "brilliant", "charming", "dreadful", "faithful", "generous", "innocent",
    "restless", "tireless", "watchful", "colorful", "cheerful", "doubtful",
    "absent", "active", "alert", "anxious", "barren", "blissful", "boundless",
    "careless", "certain", "classic", "complex", "constant", "content",
    "costly", "countless", "crafty", "cunning", "earnest", "endless",
    "fearless", "fertile", "flawless", "fluent", "foolish", "foreign",
    "fragrant", "frequent", "gallant", "ghastly", "gleaming", "gloomy",
    "handsome", "haunted", "hopeful", "hostile", "joyful", "lawless",
    "likely", "lively", "lonesome", "loyal", "modest", "mortal", "nervous",
    "noble", "painless", "passive", "playful", "pointed", "precious",
    "reckless", "rigid", "rugged", "ruthless", "shallow", "solemn",
    # ── expanded ──
    "abundant", "adequate", "agitated", "aimless", "alternate", "angular",
    "apparent", "arid", "austere", "barbed", "blatant", "buoyant",
    "candid", "chronic", "circular", "colossal", "compact", "competent",
    "composed", "concise", "concrete", "corrupt", "covert", "critical",
    "crucial", "decisive", "defiant", "deliberate", "desolate", "devoted",
    "diligent", "discreet", "distinct", "dominant", "dormant", "dramatic",
    "earnest", "elaborate", "elevated", "eloquent", "erratic", "essential",
    "evident", "excessive", "explicit", "external", "factual", "feeble",
    "fervent", "festive", "flexible", "fluent", "forceful", "fragrant",
    "frantic", "frigid", "futile", "genuine", "ghastly", "grotesque",
    "habitual", "haughty", "immense", "imminent", "implicit", "improper",
    "inferior", "informal", "insolent", "intact", "intense", "internal",
    "intricate", "inverse", "isolated", "jovial", "juvenile", "lateral",
    "lenient", "literal", "luminous", "lustrous", "marginal", "maternal",
    "mediocre", "melodic", "minimal", "mischievous", "moderate", "morbid",
    "mundane", "nominal", "obscure", "obsolete", "opulent", "organic",
    "outward", "parallel", "partial", "paternal", "peculiar", "pensive",
    "periodic", "perpetual", "placid", "plausible", "portable", "potent",
    "premature", "prevalent", "pristine", "probable", "profound", "prolific",
    "prominent", "punctual", "radical", "rational", "rampant", "reluctant",
    "renowned", "resolute", "reverent", "robust", "rustic", "scarce",
    "seasonal", "secluded", "seldom", "sensible", "serene", "skeptical",
    "slender", "sluggish", "somber", "sovereign", "specific", "sporadic",
    "steadfast", "sterile", "strenuous", "stubborn", "sublime", "superior",
    "symbolic", "tactical", "temporal", "terminal", "thorough", "tolerant",
    "tranquil", "trivial", "turbulent", "ultimate", "upright", "valiant",
    "vengeful", "verbose", "vertical", "vigilant", "volatile", "zealous",
]

ADJ_HARD = [
    "meticulous", "exquisite", "formidable", "ubiquitous", "treacherous",
    "magnificent", "spontaneous", "inconspicuous", "unprecedented",
    "extraordinary", "incomprehensible", "sophisticated", "conscientious",
    "idiosyncratic", "quintessential", "unequivocal", "ostentatious",
    "surreptitious", "contemptible", "indefatigable", "imperceptible",
    "irreconcilable", "magnanimous", "perspicacious", "phantasmagorical",
    "ambiguous", "anomalous", "benevolent", "clandestine", "contemptuous",
    "obstreperous", "derogatory", "disingenuous", "efficacious", "ephemeral",
    "fortuitous", "gratuitous", "impenetrable", "inconceivable",
    "indispensable", "ineffable", "insurmountable", "labyrinthine",
    "melancholic", "nondescript", "paradoxical", "perfunctory",
    "presumptuous", "sacrilegious", "superfluous",
    # ── expanded ──
    "acquiescent", "avaricious", "circumspect", "commensurate",
    "compendious", "conspicuous", "contemptible", "debilitating",
    "disconcerting", "disproportionate", "ecclesiastical", "equanimous",
    "fastidious", "ignominious", "imperturbable", "incommensurable",
    "incorrigible", "inexorable", "infinitesimal", "ingratiating",
    "inscrutable", "interminable", "loquacious", "magniloquent",
    "multifarious", "obsequious", "penurious", "phantasmagoric",
    "pusillanimous", "recalcitrant", "sanctimonious", "serendipitous",
    "supercilious", "sycophantic", "tempestuous", "unconscionable",
    "unpretentious", "vituperative", "vociferous",
]

# ── adverbs ──────────────────────────────────────────────────────────────────

ADV_EASY = [
    "very", "just", "well", "also", "here", "then", "soon", "still", "never",
    "always", "often", "once", "again", "away", "down", "up", "now", "fast",
    "hard", "far", "near", "back", "even", "only", "almost", "quite",
    "yet", "too", "so", "out", "off", "long", "much", "most",
    "more", "less", "last", "first", "next", "right", "left", "straight",
    "ahead", "alone", "apart", "aloud", "aside", "forth", "twice", "thus",
    # ── expanded ──
    "maybe", "perhaps", "rather", "somewhat", "instead", "indeed",
    "already", "anyway", "hence", "likewise", "meanwhile", "moreover",
    "besides", "otherwise", "surely", "lately", "mainly", "truly",
    "simply", "above", "below", "daily", "early", "late", "north",
    "south", "east", "west", "upward", "onward", "inward", "outward",
    "forward", "between", "tonight", "abroad", "ashore", "overhead",
    "halfway", "seldom",
]

ADV_MEDIUM = [
    "quickly", "slowly", "gently", "quietly", "softly", "loudly", "calmly",
    "boldly", "gladly", "sadly", "deeply", "firmly", "purely", "rarely",
    "simply", "merely", "nearly", "barely", "hardly", "clearly", "closely",
    "finally", "greatly", "largely", "neatly", "partly", "safely", "surely",
    "wholly", "widely", "eagerly", "swiftly", "bravely", "proudly",
    "sharply", "brightly", "carefully", "silently", "suddenly", "properly",
    "steadily", "patiently", "honestly", "entirely", "politely", "precisely",
    "gracefully", "endlessly", "restlessly", "faithfully", "peacefully",
    "warmly", "coolly", "fiercely", "lightly", "tightly", "loosely",
    "roughly", "smoothly", "blindly", "briefly", "broadly", "cheaply",
    "cruelly", "dimly", "fondly", "grimly", "harshly", "keenly", "madly",
    "mildly", "nobly", "plainly", "rudely", "shyly", "smartly", "stiffly",
    "strictly", "sweetly", "vaguely", "wisely", "badly", "freely", "freshly",
    "fully", "highly", "kindly", "truly", "weakly", "wildly", "actively",
    "bitterly", "commonly", "constantly", "directly", "earnestly", "formally",
    "modestly", "nervously", "solemnly",
    # ── expanded ──
    "absently", "abruptly", "aimlessly", "alertly", "anxiously",
    "awkwardly", "blissfully", "bluntly", "boastfully", "briskly",
    "cautiously", "cheerfully", "clumsily", "coarsely", "crossly",
    "daintily", "daringly", "dearly", "deeply", "densely",
    "desperately", "diligently", "dizzily", "doubtfully", "dreamily",
    "dutifully", "faintly", "feebly", "fiercely", "fluently",
    "forcefully", "frantically", "furiously", "gallantly", "gleefully",
    "graciously", "gratefully", "greedily", "grudgingly", "guiltily",
    "happily", "hastily", "heartily", "helplessly", "hesitantly",
    "hopefully", "humbly", "hungrily", "innocently", "intently",
    "jealously", "joyfully", "lazily", "lightly", "longingly",
    "lovingly", "loyally", "merrily", "mildly", "mockingly",
    "obediently", "painfully", "passionately", "playfully", "pleasantly",
    "promptly", "quietly", "recklessly", "reluctantly", "restlessly",
    "rigidly", "savagely", "selfishly", "sternly", "stubbornly",
    "tenderly", "thankfully", "thoughtfully", "timidly", "urgently",
    "vaguely", "viciously", "wearily", "willingly", "wrathfully",
]

# ── adverbs (hard) ───────────────────────────────────────────────────────────

ADV_HARD = [
    "meticulously", "spontaneously", "simultaneously", "unquestionably",
    "conscientiously", "indiscriminately", "inconspicuously", "magnanimously",
    "surreptitiously", "extraordinarily", "incomprehensibly", "unequivocally",
    "disproportionately", "incontrovertibly", "characteristically",
    "ostentatiously", "perfunctorily", "perspicaciously", "presumptuously",
    "quintessentially", "idiosyncratically", "imperceptibly", "irreconcilably",
    "fortuitously", "gratuitously", "clandestinely", "efficaciously",
    "unceremoniously", "disingenuously", "insurmountably",
    # ── expanded ──
    "categorically", "ceremoniously", "circumspectly", "commensurately",
    "conspicuously", "contemptuously", "deliberately", "discriminately",
    "extemporaneously", "ignominiously", "imperturbably", "incorrigibly",
    "inexorably", "ingratiatingly", "inscrutably", "interminably",
    "loquaciously", "magniloquently", "obsequiously", "parsimoniously",
    "perfunctorily", "pusillanimously", "recalcitrantly", "sanctimoniously",
    "serendipitously", "superciliously", "sycophantically", "tempestuously",
    "unconscionably", "vociferously",
]

# ── prepositions ─────────────────────────────────────────────────────────────

PREPOSITIONS = [
    "in", "on", "at", "by", "to", "for", "from", "with", "near", "past",
    "through", "across", "around", "along", "above", "below", "under",
    "beside", "behind", "beyond", "between", "toward", "against", "among",
    "beneath", "inside", "outside", "within", "without", "before", "after",
    # ── expanded ──
    "amid", "amidst", "alongside", "atop", "despite", "during", "except",
    "into", "onto", "opposite", "over", "throughout", "underneath", "upon",
]

# ── time phrases ─────────────────────────────────────────────────────────────

TIME_PHRASES = [
    "that morning", "that evening", "that night", "that afternoon",
    "last summer", "last winter", "last spring", "every morning",
    "every evening", "every winter", "for many years", "for a long time",
    "at dawn", "at dusk", "at midnight", "at noon", "on that day",
    "in those days", "long ago", "years later", "the next morning",
    "the following day", "one quiet evening", "on a cold night",
    "during the storm", "before sunrise", "after sunset", "by then",
    "at that moment", "without warning", "all at once", "once again",
    "that autumn", "last autumn", "every afternoon", "for several days",
    "at first light", "in the distance", "the night before", "one summer day",
    "on a clear morning", "after the rain", "before nightfall", "at twilight",
    "the week before", "many months later", "in early spring",
    "late that night", "on the final day", "from that day on",
    # ── expanded ──
    "one winter night", "on a foggy morning", "after many hours",
    "before the first snow", "in the dead of night", "as the sun rose",
    "when the clock struck", "during the harvest", "at the break of dawn",
    "in the fading light", "on a windswept hill", "through the long night",
    "by early afternoon", "under a crescent moon", "past the witching hour",
    "on a summer evening", "toward the end of day", "in the stillness",
    "as autumn approached", "when the fog lifted", "before the tide came",
    "after the last bell", "in the small hours", "on a bitter morning",
    "as the years passed", "when spring arrived", "in the weeks that followed",
    "just before midnight", "on the eve of winter", "at the turn of the hour",
    "through the afternoon", "as darkness settled", "upon the hillside",
    "with the coming of dawn", "during the quiet hours",
]

# ── pool builder ─────────────────────────────────────────────────────────────

def _pool(easy, medium=None, hard=None, difficulty="medium"):
    """Build a cumulative word pool based on difficulty."""
    if difficulty == "easy":
        return easy
    elif difficulty == "medium":
        return easy + (medium or [])
    else:
        return easy + (medium or []) + (hard or [])


def get_pools(difficulty="medium"):
    """Return all word category pools for a given difficulty."""
    return {
        "noun": _pool(NOUNS_EASY, NOUNS_MEDIUM, NOUNS_HARD, difficulty),
        "nouns": _pool(NOUNS_PL_EASY, NOUNS_PL_MEDIUM, NOUNS_PL_HARD, difficulty),
        "name": NAMES,
        "v_past": _pool(VERBS_PAST_EASY, VERBS_PAST_MEDIUM, VERBS_PAST_HARD, difficulty),
        "v_pres": _pool(VERBS_PRES_EASY, VERBS_PRES_MEDIUM, difficulty=difficulty),
        "v_base": _pool(VERBS_BASE_EASY, VERBS_BASE_MEDIUM, difficulty=difficulty),
        "v_ing": _pool(VERBS_ING_EASY, VERBS_ING_MEDIUM, difficulty=difficulty),
        "adj": _pool(ADJ_EASY, ADJ_MEDIUM, ADJ_HARD, difficulty),
        "adv": _pool(ADV_EASY, ADV_MEDIUM, ADV_HARD, difficulty),
        "prep": PREPOSITIONS,
        "time": TIME_PHRASES,
    }
